version: "3.9"
services:
    web:
        build: .
        ports:
            - "3001:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Baris54!*"
            ACCEPT_EULA: "Y"